#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="baltanet_Games")]
public partial class HighScoresDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertMegaJump_Highscore(MegaJump_Highscore instance);
  partial void UpdateMegaJump_Highscore(MegaJump_Highscore instance);
  partial void DeleteMegaJump_Highscore(MegaJump_Highscore instance);
  #endregion
	
	public HighScoresDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["baltanet_GamesConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public HighScoresDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HighScoresDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HighScoresDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public HighScoresDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<MegaJump_Highscore> MegaJump_Highscores
	{
		get
		{
			return this.GetTable<MegaJump_Highscore>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="baltanet_balta.MegaJump_Highscores")]
public partial class MegaJump_Highscore : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _HighscoreID;
	
	private string _HighScore;
	
	private string _Name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHighscoreIDChanging(int value);
    partial void OnHighscoreIDChanged();
    partial void OnHighScoreChanging(string value);
    partial void OnHighScoreChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    #endregion
	
	public MegaJump_Highscore()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighscoreID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int HighscoreID
	{
		get
		{
			return this._HighscoreID;
		}
		set
		{
			if ((this._HighscoreID != value))
			{
				this.OnHighscoreIDChanging(value);
				this.SendPropertyChanging();
				this._HighscoreID = value;
				this.SendPropertyChanged("HighscoreID");
				this.OnHighscoreIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HighScore", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string HighScore
	{
		get
		{
			return this._HighScore;
		}
		set
		{
			if ((this._HighScore != value))
			{
				this.OnHighScoreChanging(value);
				this.SendPropertyChanging();
				this._HighScore = value;
				this.SendPropertyChanged("HighScore");
				this.OnHighScoreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
